In [ ]:
#1.Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
#chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)
import numpy as np

# Tạo ma trận 3x3 với số nguyên ngẫu nhiên từ 0 đến 20
arr = np.random.randint(0, 21, size=(3, 3))

print("Ma trận:")
print(arr)

# Kiểm tra tất cả phần tử khác 0
check = np.all(arr != 0)

print("Tất cả phần tử khác 0:", check)

Ma trận:
[[14 16 14]
 [ 4 16 16]
 [14  6  3]]
Tất cả phần tử khác 0: True


In [ ]:
#2.Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
#chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)

# Tạo ma trận 3x3 với số nguyên ngẫu nhiên trong [0, 20]
arr = np.random.randint(0, 21, (3, 3))

print("Ma trận:")
print(arr)

# Kiểm tra tất cả phần tử khác 0
if np.all(arr != 0):
    print("Tất cả phần tử đều khác 0")
else:
    print("Có phần tử bằng 0")

Ma trận:
[[15 12 10]
 [ 6  4  9]
 [ 7  1  2]]
Tất cả phần tử đều khác 0


In [ ]:
pip install pandas

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2


In [ ]:
#nối 2 DataFrame
df1 = pd.DataFrame({'Name': ['John', 'Jame', 'Paul'],
                    'Age': [25, 18, 23]}, index = [0, 1, 2])
df2 = pd.DataFrame({'Name': ['Adam', 'Jame'],
                    'Age': [26, 11]}, index = [3, 4])
df_contact = pd.concat([df1, df2])
print('Concat two DataFrame\n', df_contact)
#xóa những giá trị ở cột Name trùng nhau
print('Drop dupplicatevalues in DataFrame\n', df_contact.drop_duplicates('Name'))
#sắp xếp theo cột
print('Sort values in DataFrame\n', df_contact.sort_values('Age'))
#đổi tên cột
df_rename = df_contact.rename(colums = {'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concat two DataFrame
    Name  Age
0  John   25
1  Jame   18
2  Paul   23
3  Adam   26
4  Jame   11
Drop dupplicatevalues in DataFrame
    Name  Age
0  John   25
1  Jame   18
2  Paul   23
3  Adam   26
Sort values in DataFrame
    Name  Age
4  Jame   11
1  Jame   18
2  Paul   23
0  John   25
3  Adam   26


TypeError: DataFrame.rename() got an unexpected keyword argument 'colums'

In [ ]:
#3.Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater,
#numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [ ]:
#4.Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5
a = np.array([1]* 10 + [0]*10 + [5]*10)
print(a)


[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]


In [ ]:
#5.Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]
a = np.arange(30, 71, 2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
#6.Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0)
#(Tìm hiểu hàm identity của numpy)
i = np.identity(3)
print(i)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#7.Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử
#đầu và cuối
# Tạo mảng 10 phần tử trong khoảng [15, 55]
a = np.linspace(15, 55, 10, dtype=int)

print("Mảng đầy đủ:", a)

# In các giá trị trừ phần tử đầu và cuối
print("Các giá trị trừ phần tử đầu và cuối:", a[1:-1])


Mảng đầy đủ: [15 19 23 28 32 37 41 46 50 55]
Các giá trị trừ phần tử đầu và cuối: [19 23 28 32 37 41 46 50]


In [ ]:
#8.Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20] và đổi dấu những số nằm trong
#khoảng [9, 15]
a = np.linspace(0, 20, 20, dtype= int)
print('In mảng đầy đủ:', a)
a[(a >= 9) & (a <= 15)] *= -1
print('In mảng sau khi đổi dấu trong khoảng [9, 15]:', a)

In mảng đầy đủ: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 20]
In mảng sau khi đổi dấu trong khoảng [9, 15] [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  20]


In [ ]:
#9.Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]
a = np.random.randint(10, 21 , size= (3, 4))
print('Ma trận sau 3x4:', a)

Ma trận sau 3x4: [[18 20 13 14]
 [16 20 18 18]
 [19 19 12 11]]


In [ ]:
#10.Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong có
#giá trị 0
a = np.zeros((10, 10), dtype= int)
a[0, :] = 1
a[-1, :] = 1
a[:, 0] = 1
a[:, -1] = 1
print('Ma trận 10x10 biên giá trị là 1 và phần tử trong có giá trị 0:\n',a)

Ma trận 10x10 biên giá trị là 1 và phần tử trong có giá trị 0:
 [[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
#11.Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chính là 1, 2, 3, 4, 5. (tìm hiểu
#hàm diag của numpy)
import numpy as np
diagonal_elements = [1, 2, 3, 4, 5]
a = np.diag(diagonal_elements)
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
#12.Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum
#của numpy)
a = np.random.randint(0, 10, (3, 3, 3))
print('Mảng 3x3x3:\n', a)
sum_rows = a.sum(axis = 1)
print('\nTổng theo từng dòng:\n', sum_rows)
sum_columns = a.sum(axis = 2)
print('\nTống theo từng cột:\n', sum_columns)


Mảng 3x3x3:
 [[[2 3 8]
  [7 9 7]
  [5 4 1]]

 [[7 7 7]
  [0 2 8]
  [1 2 8]]

 [[7 7 5]
  [1 9 0]
  [4 0 2]]]

Tổng theo từng dòng:
 [[14 16 16]
 [ 8 11 23]
 [12 16  7]]

Tống theo từng cột:
 [[13 23 10]
 [21 10 11]
 [19 10  6]]


In [ ]:
#13. Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)
vector1 = np.random.randint(0, 10, 10)
vector2 = np.random.randint(0, 10, 10)
print('Vector 1:', vector1)
print('Vector 2:', vector2)
inner_product = np.dot(vector1, vector2)
print('Inner product:', inner_product)

Vector 1: [7 8 8 8 5 6 7 3 9 7]
Vector 2: [2 0 0 2 4 3 5 0 0 4]
Inner product: 131


In [ ]:
#14. Tạo ma trận A= 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dòng của
#ma trận A
a = np.random.randint(0, 10, (4, 3))
print("Ma trận A:\n", a)
y = np.random.randint(0, 10, 3)
print("\nVector y:", y)
result = a + y
print("\nKết quả sau khi cộng y vào từng dòng của A:\n", result)


Ma trận A:
 [[5 9 7]
 [0 4 4]
 [5 5 9]
 [8 6 1]]

Vector y: [3 1 6]

Kết quả sau khi cộng y vào từng dòng của A:
 [[ 8 10 13]
 [ 3  5 10]
 [ 8  6 15]
 [11  7  7]]


In [ ]:
#15. Viết chương trình Pandas để cộng, trừ, nhân, chia 2 Series : [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]
a = pd.Series([2,4,6,8,10])
b = pd.Series([1,3,5,7,10])
print('Series 1:\n', a)
print('Series 2:\n', b)
cong = a + b
print('\nCộng:\n', cong)
tru = a - b
print('\nTru:\n', tru)
nhan = a * b
print('\nNhân:\n', nhan)
chia = a / b
print('\nChia:\n', chia)


Series 1:
 0     2
1     4
2     6
3     8
4    10
dtype: int64
Series 2:
 0     1
1     3
2     5
3     7
4    10
dtype: int64

Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64

Tru:
 0    1
1    1
2    1
3    1
4    0
dtype: int64

Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64

Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


In [ ]:
#16. Viết chương trình Pandas chuyển đổi cột đầu tiên thành Series (Tìm hiểu thuộc tính ix của
#pandas)

data = {
    "col1": [1, 2, 3, 4, 7, 11],
    "col2": [4, 5, 6, 9, 5, 0],
    "col3": [7, 5, 8, 12, 1, 11]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)


col1_series = df["col1"]
print("\nCột đầu tiên dưới dạng Series:\n", col1_series)


DataFrame:
    col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

Cột đầu tiên dưới dạng Series:
 0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


In [ ]:
#17. Viết chương trình Pandas sắp xếp theo cột của DataFrame 4 x 3 ngẫu nhiên
df = pd.DataFrame(np.random.randint(0, 10, (4, 3)), columns=["col1", "col2", "col3"])
print("DataFrame ban đầu:\n", df)

sorted_df_col1 = df.sort_values(by="col1")
print("\nSắp xếp theo col1:\n", sorted_df_col1)
sorted_df_col2 = df.sort_values(by="col2")
print("\nSắp xếp theo col2:\n", sorted_df_col2)

sorted_df_col3_desc = df.sort_values(by="col3", ascending=False)
print("\nSắp xếp theo col3 (giảm dần):\n",sorted_df_col3_desc )

DataFrame ban đầu:
    col1  col2  col3
0     4     7     5
1     5     4     6
2     0     1     9
3     3     2     0

Sắp xếp theo col1:
    col1  col2  col3
2     0     1     9
3     3     2     0
0     4     7     5
1     5     4     6

Sắp xếp theo col2:
    col1  col2  col3
2     0     1     9
3     3     2     0
1     5     4     6
0     4     7     5

Sắp xếp theo col3 (giảm dần):
    col1  col2  col3
2     0     1     9
1     5     4     6
0     4     7     5
3     3     2     0


In [ ]:
#18. Viết chương trình Pandas thay đổi index của một Series (dùng pandas.reindex)
a = pd.Series([1, 2, 3, 4, 5], index = ['A', 'B', 'C', 'D', 'E'])
print('Series ban đầu:\n', a)
new_index = ['B', 'A', 'C', 'D', 'E']
s_reindexed = a.reindex(new_index)
print('\nSeries sau khi reindex:\n', s_reindexed)

Series ban đầu:
 A    1
B    2
C    3
D    4
E    5
dtype: int64

Series sau khi reindex:
 B    2
A    1
C    3
D    4
E    5
dtype: int64


In [ ]:
#19. Viết chương trình Pandas tìm những phần tử trong Series x mà không có trong Series y (Tìm
#hiểu hàm isin của pandas)
a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([2, 4, 6, 8, 10])
print('Series a:\n', a)
print('\nSeries a:\n', b)
kq = a[~a.isin(b)]
print('\nKết quả các phần tử của a không có trong b:\n', kq)

Series a:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

Series a:
 0     2
1     4
2     6
3     8
4    10
dtype: int64

Kết quả các phần tử của a không có trong b:
 0    1
2    3
4    5
dtype: int64


In [ ]:
#20. Tìm hiểu phép toán numpy.union1d, numpy.intersect1d (hội, giao) và viết chương trình minh
#họa 2 hàm này trên 2 Series x, y ngẫu nhiên có 20 phần tử
x = pd.Series(np.random.randint(0, 30, 20))
y = pd.Series(np.random.randint(0,30, 20))
print('Series x:\n', x)
print('\nSeries y:\n', y)
union_res = np.union1d(x, y)
print('\nPhép hội:"\n', union_res)
intersection_res = np.intersect1d(x, y)
print('\nPhép giao:\n', intersection_res)

Series x:
 0     10
1      7
2     29
3     15
4      0
5     13
6      8
7      0
8     22
9     28
10     8
11    23
12    25
13    17
14     1
15    17
16    20
17    25
18    13
19    27
dtype: int64

Series y:
 0     25
1     16
2     20
3     13
4      7
5     20
6     17
7      1
8     12
9     10
10    10
11    24
12     5
13     1
14    26
15    13
16    25
17    11
18    11
19    28
dtype: int64

Phép hội:"
 [ 0  1  5  7  8 10 11 12 13 15 16 17 20 22 23 24 25 26 27 28 29]

Phép giao:
 [ 1  7 10 13 17 20 25 28]


In [ ]:
#21. Viết chương trình Pandas thêm series y vào series x theo chiều dọc (vertical), chiều ngang
#(horizontal) (Tìm hiểu hàm append và concat của pandas)
# Tạo 2 Series
x = pd.Series([1, 2, 3, 4, 5])
y = pd.Series([6, 7, 8, 9, 10])

print("Series x:\n", x)
print("\nSeries y:\n", y)

vertical_concat = pd.concat([x, y], ignore_index=True)
print("\nGhép theo chiều dọc (concat):\n", vertical_concat)

# --- Ghép theo chiều ngang (horizontal) ---
horizontal_concat = pd.concat([x, y], axis=1)
print("\nGhép theo chiều ngang (concat):\n", horizontal_concat)

Series x:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

Series y:
 0     6
1     7
2     8
3     9
4    10
dtype: int64

Ghép theo chiều dọc (concat):
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

Ghép theo chiều ngang (concat):
    0   1
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10


In [9]:
#22. Viết chương trình Pandas tạo và hiển thị dữ liệu DataFrame
import pandas as pd
import numpy as np
data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
             'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attemps': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

print(df)

        name  score  attemps qualify
a  Anastasia   12.5        1     yes
b       Dima    9.0        3      no
c  Katherine   16.5        2     yes
d      James    NaN        3      no
e      Emily    9.0        2      no
f    Michael   20.0        3     yes
g    Matthew   14.5        1     yes
h      Laura    NaN        1      no
i      Kevin    8.0        2      no
j      Jonas   19.0        1     yes


In [3]:
#23. Từ bài 22, cho biết 3 dòng đầu tiên
print(df.head(3))

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [4]:
#24. Từ bài 22, chọn cột ‘name’ và ‘score’
print(df[['name', 'score']])

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [10]:
#25. Từ bài 22, chọn những dòng có attemps > 2
print(df[df['attemps'] > 2])

      name  score  attemps qualify
b     Dima    9.0        3      no
d    James    NaN        3      no
f  Michael   20.0        3     yes


In [11]:
#26. Từ bài 22, cho biết số dòng, số cột của DataFrame
print(df.shape)

(10, 4)


In [12]:
#27. Từ bài 22, cho biết những dòng có score là NaN (tìm hiểu hàm isnull của pandas)
print(df[df['score'].isnull()])

    name  score  attemps qualify
d  James    NaN        3      no
h  Laura    NaN        1      no


In [13]:
#28. Từ bài 22, cho biết những dòng có score trong khoảng (15, 20) (tìm hiểu hàm between của
#pandas)
print(df[df['score'].between(15, 20, inclusive='neither')])

        name  score  attemps qualify
c  Katherine   16.5        2     yes
j      Jonas   19.0        1     yes


In [15]:
#29. Từ bài 22, cho biết những dòng có attemp > 2 và score trong khoảng (15, 20)
print(df[(df['attemps'] > 2) & (df['score'].between(15, 20, inclusive='neither'))])

Empty DataFrame
Columns: [name, score, attemps, qualify]
Index: []


In [16]:
#30. Từ bài 22, cho biết những thay đổi giá trị dòng ‘d’, cột score là 19 (tìm hiểu hàm loc của pandas)
df.loc['d', 'score'] = 19
print(df)

        name  score  attemps qualify
a  Anastasia   12.5        1     yes
b       Dima    9.0        3      no
c  Katherine   16.5        2     yes
d      James   19.0        3      no
e      Emily    9.0        2      no
f    Michael   20.0        3     yes
g    Matthew   14.5        1     yes
h      Laura    NaN        1      no
i      Kevin    8.0        2      no
j      Jonas   19.0        1     yes
