In [1]:
#1. Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0
import tensorflow as tf

tensor = tf.zeros((2, 3))
print(tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [2]:
#2. Cho X = [[1, 2, 3], [4, 5, 6]], hãy tạo tensor có kích thước và dtype như X với các phần tử được
#gán 0

X = tf.constant([[1, 2, 3], [4, 5, 6]])

tensor = tf.zeros_like(X)
print(tensor)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [3]:
#3. Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5
tensor = tf.fill((3, 2), 5)
print(tensor)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


In [4]:
#4. Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]
a = tf.constant([6, 8, 10])
tensor = tf.tile(a, [17])[:50]

print(tensor)

tf.Tensor(
[ 6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10
  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10
  6  8], shape=(50,), dtype=int32)


In [5]:
#5. Tạo một tensor 1-chiều có giá trị như [10, 12, 14, ..., 100]
tensor = tf.range(10, 101, 2)
print(tensor)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


In [6]:
#6. Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối normal với mean=0,
#standard deviation = 2
tensor = tf.random.normal(shape=(3, 2), mean=0.0, stddev=2.0)
print(tensor)

tf.Tensor(
[[-1.1151713   1.2084576 ]
 [-0.86747384 -0.28926465]
 [-0.6201994   2.6269107 ]], shape=(3, 2), dtype=float32)


In [7]:
#7. Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối uniform trong phạm vi
#[0, 2]
tensor = tf.random.uniform(shape=(3, 2), minval=0.0, maxval=2.0)
print(tensor)

tf.Tensor(
[[1.1920056  0.46646166]
 [1.5652072  1.072962  ]
 [0.45031714 0.18035722]], shape=(3, 2), dtype=float32)


In [8]:
#8. Cho tensor X = [[1, 2], [3, 4], [5, 6]]. Hãy shuffle X theo chiều thứ nhất (sử dụng
#random_shuffle)
x = tf.constant([[1, 2], [3, 4], [5, 6]])
shuffled = tf.random.shuffle(x)
print(shuffled)

tf.Tensor(
[[5 6]
 [3 4]
 [1 2]], shape=(3, 2), dtype=int32)


In [9]:
#9. Hãy tạo ngẫu nhiên tensor kích thước (10, 10, 3). Cắt thành tensor có kích thước (5, 5, 3) (sử
#dụng random_crop)
x = tf.random.uniform((10, 10, 3))
cropped = tf.image.random_crop(x, size=(5, 5, 3))
print(cropped)

tf.Tensor(
[[[0.7701429  0.71988535 0.12291574]
  [0.59067595 0.33192647 0.263088  ]
  [0.9676486  0.39876425 0.23508108]
  [0.68455565 0.40327954 0.03514326]
  [0.12072182 0.00397658 0.43084526]]

 [[0.40662658 0.1988759  0.5676788 ]
  [0.79264355 0.0480448  0.53198373]
  [0.24111724 0.67593074 0.8344556 ]
  [0.90302944 0.62784755 0.65006196]
  [0.5607405  0.45307314 0.03101242]]

 [[0.16561258 0.5549797  0.6316823 ]
  [0.37160754 0.8886498  0.8106922 ]
  [0.4323727  0.03983986 0.48900437]
  [0.5945947  0.40593767 0.75561094]
  [0.68364584 0.6657262  0.31516886]]

 [[0.6047665  0.7466717  0.97075117]
  [0.16638696 0.9123359  0.8127892 ]
  [0.724802   0.8813274  0.70542336]
  [0.7530371  0.05937624 0.16367435]
  [0.9960319  0.99740374 0.4402722 ]]

 [[0.280645   0.9778913  0.6390796 ]
  [0.07865715 0.83511496 0.36222255]
  [0.92777896 0.68078625 0.80430007]
  [0.05865788 0.4639697  0.37881076]
  [0.2864461  0.7464962  0.3133545 ]]], shape=(5, 5, 3), dtype=float32)


In [10]:
#10. Tạo ngẫu nhiên hai tensor 1-chiều x, y có 5 phần tử. Trả về x + y nếu x < y, và x – y nếu x > y
x = tf.random.uniform((5,), minval=0, maxval=10, dtype=tf.int32)
y = tf.random.uniform((5,), minval=0, maxval=10, dtype=tf.int32)
result = tf.where(x < y, x + y, x - y)
print("x:", x)
print("y:", y)
print("result:", result)

x: tf.Tensor([7 9 9 0 4], shape=(5,), dtype=int32)
y: tf.Tensor([8 6 7 1 3], shape=(5,), dtype=int32)
result: tf.Tensor([15  3  2  1  1], shape=(5,), dtype=int32)


In [11]:
#11. Tạo ngẫu nhiên 2 tensor kích thước x = (3, 2) và giá trị trong khoảng [5, 10], y = (2, 3) và giá
#trị [15, 20] tương ứng. Hãy giữ giá trị đường chéo của x và thực hiện x + y
x = tf.random.uniform((3, 2), minval=5, maxval=11, dtype=tf.int32)
y = tf.random.uniform((2, 3), minval=15, maxval=21, dtype=tf.int32)
mask = tf.linalg.diag(tf.ones(min(x.shape), dtype=tf.int32))
mask = tf.pad(mask, [[0, x.shape[0]-mask.shape[0]], [0, x.shape[1]-mask.shape[1]]])
x_diag = x * mask
result = tf.matmul(x_diag, y)
print("x:\n", x)
print("x (giữ đường chéo):\n", x_diag)
print("y:\n", y)
print("Kết quả x @ y:\n", result)

x:
 tf.Tensor(
[[9 5]
 [6 9]
 [9 6]], shape=(3, 2), dtype=int32)
x (giữ đường chéo):
 tf.Tensor(
[[9 0]
 [0 9]
 [0 0]], shape=(3, 2), dtype=int32)
y:
 tf.Tensor(
[[17 15 18]
 [15 20 17]], shape=(2, 3), dtype=int32)
Kết quả x @ y:
 tf.Tensor(
[[153 135 162]
 [135 180 153]
 [  0   0   0]], shape=(3, 3), dtype=int32)


In [12]:
#12. Viết hàm tạo 2 tensor ngẫu nhiên có kích thước x = (3, 2, 2), y = (3, 2, 2). Viết hàm tính cộng,
#trừ, nhân, chia sau đó chuyển các hàm này vào trong graph.
def create_tensors():
    x = tf.random.uniform((3, 2, 2))
    y = tf.random.uniform((3, 2, 2))
    return x, y
@tf.function
def tensor_ops(x, y):
    add = x + y
    sub = x - y
    mul = x * y
    div = x / y
    return add, sub, mul, div
x, y = create_tensors()
add, sub, mul, div = tensor_ops(x, y)
print("x:\n", x)
print("y:\n", y)
print("x + y:\n", add)
print("x - y:\n", sub)
print("x * y:\n", mul)
print("x / y:\n", div)

x:
 tf.Tensor(
[[[0.9276217  0.19339478]
  [0.7886809  0.91178906]]

 [[0.62763774 0.71552503]
  [0.77235353 0.6752788 ]]

 [[0.8477731  0.51672196]
  [0.38413548 0.05206466]]], shape=(3, 2, 2), dtype=float32)
y:
 tf.Tensor(
[[[0.9468876  0.01410425]
  [0.26789045 0.6319752 ]]

 [[0.05595446 0.42208672]
  [0.5110861  0.63746476]]

 [[0.42701375 0.53026557]
  [0.66256285 0.36142433]]], shape=(3, 2, 2), dtype=float32)
x + y:
 tf.Tensor(
[[[1.8745093  0.20749903]
  [1.0565714  1.5437642 ]]

 [[0.6835922  1.1376117 ]
  [1.2834396  1.3127435 ]]

 [[1.2747868  1.0469875 ]
  [1.0466983  0.41348898]]], shape=(3, 2, 2), dtype=float32)
x - y:
 tf.Tensor(
[[[-0.01926589  0.17929053]
  [ 0.52079046  0.2798139 ]]

 [[ 0.5716833   0.29343832]
  [ 0.26126742  0.03781402]]

 [[ 0.42075932 -0.01354361]
  [-0.27842736 -0.30935967]]], shape=(3, 2, 2), dtype=float32)
x * y:
 tf.Tensor(
[[[0.87835354 0.00272769]
  [0.2112801  0.576228  ]]

 [[0.03511913 0.3020136 ]
  [0.39473915 0.43046644]]

 [[0.36201078

In [13]:
#13. Xây dựng model để tính tổng hai tensor x, y
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Add
input_x = Input(shape=(2,))
input_y = Input(shape=(2,))
output = Add()([input_x, input_y])
model = Model(inputs=[input_x, input_y], outputs=output)
x = tf.constant([[1.0, 2.0]])
y = tf.constant([[3.0, 4.0]])

result = model([x, y])
print(result)

tf.Tensor([[4. 6.]], shape=(1, 2), dtype=float32)


In [14]:
#14. Xây dựng model để tính hiệu và tích hai tensor x, y
from tensorflow.keras.layers import Subtract, Multiply
input_x = Input(shape=(2,))
input_y = Input(shape=(2,))
sub = Subtract()([input_x, input_y])
mul = Multiply()([input_x, input_y])
model = Model(inputs=[input_x, input_y], outputs=[sub, mul])
x = tf.constant([[5.0, 6.0]])
y = tf.constant([[2.0, 3.0]])

result_sub, result_mul = model([x, y])

print("Hiệu:", result_sub)
print("Tích:", result_mul)

Hiệu: tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)
Tích: tf.Tensor([[10. 18.]], shape=(1, 2), dtype=float32)


In [15]:
#15. Xây dựng model để tính chu vi hình chữ nhật P = (a +b) * 2
from tensorflow.keras.layers import Lambda
a = Input(shape=(1,))
b = Input(shape=(1,))
sum_ab = Add()([a, b])

P = Lambda(lambda x: x * 2)(sum_ab)

model = Model(inputs=[a, b], outputs=P)
a_val = tf.constant([[3.0]])
b_val = tf.constant([[4.0]])

result = model([a_val, b_val])
print("Chu vi:", result)

Chu vi: tf.Tensor([[14.]], shape=(1, 1), dtype=float32)


In [16]:
#16. Xây dựng model để tính diện tích toàn phần hình hộp chữ nhật
#Sxung quanh = (a + b) * c * 2
#Stoàn phần = (a * b) * 2 + Sxung quanh
from tensorflow.keras.layers import Multiply
a = Input(shape=(1,))
b = Input(shape=(1,))
c = Input(shape=(1,))

sum_ab = Add()([a, b])

sxq = Multiply()([sum_ab, c])
sxq = Lambda(lambda x: x * 2)(sxq)
ab = Multiply()([a, b])
two_ab = Lambda(lambda x: x * 2)(ab)

stp = Add()([two_ab, sxq])

model = Model(inputs=[a, b, c], outputs=stp)

# Test
a_val = tf.constant([[2.0]])
b_val = tf.constant([[3.0]])
c_val = tf.constant([[4.0]])

result = model([a_val, b_val, c_val])
print("Diện tích toàn phần:", result)

Diện tích toàn phần: tf.Tensor([[52.]], shape=(1, 1), dtype=float32)


In [28]:
#17. Xây dựng model chứng minh hai cạnh bên hình thang song song theo điều kiện
import tensorflow as tf
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Lambda

AD = Input(shape=(1,))
BC = Input(shape=(1,))
AB = Input(shape=(1,))
CD = Input(shape=(1,))

# So sánh
cond1 = Lambda(lambda x: tf.abs(x[0] - x[1]) < 1e-5,
               output_shape=(1,))([AD, BC])

cond2 = Lambda(lambda x: tf.abs(x[0] - x[1]) < 1e-5,
               output_shape=(1,))([AB, CD])

# Logical AND (phải chỉ rõ shape)
parallel = Lambda(lambda x: tf.logical_and(x[0], x[1]),
                  output_shape=(1,))([cond1, cond2])

model = Model(inputs=[AD, BC, AB, CD], outputs=parallel)
import tensorflow as tf

AD_val = tf.constant([[3.0]])
BC_val = tf.constant([[3.0]])
AB_val = tf.constant([[5.0]])
CD_val = tf.constant([[5.0]])

result = model([AD_val, BC_val, AB_val, CD_val])
print(result)

tf.Tensor([[ True]], shape=(1, 1), dtype=bool)


In [ ]:
#18. Xây dựng model chứng minh hai cạnh bên hình thang bằng nhau theo điều kiện
import tensorflow as tf
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Lambda

AD = Input(shape=(1,))
BC = Input(shape=(1,))
AB = Input(shape=(1,))
CD = Input(shape=(1,))

cond1 = Lambda(lambda x: tf.abs(x[0] - x[1]) < 1e-5,
               output_shape=(1,))([AD, BC])

cond2 = Lambda(lambda x: tf.abs(x[0] - x[1]) < 1e-5,
               output_shape=(1,))([AB, CD])

parallel = Lambda(lambda x: tf.logical_and(x[0], x[1]),
                  output_shape=(1,))([cond1, cond2])

model = Model(inputs=[AD, BC, AB, CD], outputs=parallel)
AB_val = tf.constant([[5.0]])
CD_val = tf.constant([[5.0]])
AD_val = tf.constant([[3.0]])
BC_val = tf.constant([[3.0]])

print(model([AB_val, CD_val, AD_val, BC_val]))

tf.Tensor([[ True]], shape=(1, 1), dtype=bool)


In [33]:
#19. Xây dựng model chứng minh NA = NC theo mô tả sau với AM, MB, AN, NC là đầu vào
import tensorflow as tf
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Lambda

AM = Input(shape=(1,))
MB = Input(shape=(1,))
AN = Input(shape=(1,))
NC = Input(shape=(1,))
cond1 = Lambda(
    lambda x: tf.less(tf.abs(x[0] - x[1]), 1e-5),
    output_shape=(1,)
)([AM, MB])

cond2 = Lambda(
    lambda x: tf.less(tf.abs(x[0] - x[1]), 1e-5),
    output_shape=(1,)
)([AN, NC])

result = Lambda(
    lambda x: tf.logical_and(x[0], x[1]),
    output_shape=(1,)
)([cond1, cond2])

model = Model(inputs=[AM, MB, AN, NC], outputs=result)

# Test
AM_val = tf.constant([[2.0]])
MB_val = tf.constant([[2.0]])
AN_val = tf.constant([[3.0]])
NC_val = tf.constant([[3.0]])

print("Kết quả NA = NC:", model([AM_val, MB_val, AN_val, NC_val]))

Kết quả NA = NC: tf.Tensor([[ True]], shape=(1, 1), dtype=bool)
